nginx_autossl:
  image: oubenruing/nginx_autossl:latest
  restart: always
  environment:
    UPSTREAM: 127.0.0.1:8080
    SERVERNAME: "*.example.com"
    EMAILS: ""
    CLOUDFLAREAPIEMAIL: ""
    CLOUDFLAREAPIKEY: ""
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - "/etc/letsencrypt"